repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: flake8
      - id: check-ast
      - id: check-merge-conflict
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.4.2
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  # - repo: https://github.com/pre-commit/mirrors-prettier
  #   rev: ""
  #   hooks:
  #     - id: prettier
  # - repo: https://github.com/motet-a/jinjalint
  #   rev: ""
  #   hooks:
  #     - id: jinjalint
